Issue 110
ruuvi/ruuvi.gateway_esp.c pull request #115
Opened 2020-09-11 19:02 UTC by opsationby

2020-09-14 12:28 UTC, ojousima requested changes

2020-09-14 12:28 UTC, ojousima commented on main/adv_post.c
> +static void
Please add a comment describing when this function gets called and what *arg is expected to contain.

2020-09-14 12:28 UTC, ojousima commented on main/adv_post.c
> +adv_post_send_device_id(void *arg)
Please add a comment describing when this function gets called and what *arg is expected to contain

2020-09-15 13:06 UTC, ojousima commented
Add to whitelist

2020-09-15 13:24 UTC, ojousima commented
Add to whitelist

2020-09-15 14:07 UTC, ojousima commented
retest this please

2020-09-15 14:18 UTC, ojousima commented
retest this please

2020-09-16 09:39 UTC, ojousima commented
Tested on Gateway A1 with nRF v0.4.0 by @theBASTI0N.

2020-09-16 09:39 UTC, ojousima approved these changes

2020-09-20 23:30 UTC, TheSomeMan approved these changes

2020-09-20 23:34 UTC, merged